In [2]:
# Import the dependencies.
from pathlib import Path
from sqlalchemy import create_engine, text, Column, Integer, String, Date
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import Session
import pandas as pd
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Needed for decision tree visualization
import pydotplus
from IPython.display import Image

In [3]:
# Load student data
def LoadData():
    #Load PostGres database
    userName = "postgres"
    password = "postgres" #use your postgres password if you changed it
    database = "MLearning" 
    engine = create_engine(f"postgresql+psycopg2://{userName}:{password}@localhost:5432/{database}")
    conn = engine.connect()

    #Pull the data into pandas. We are filtering by the period    
    try:
        # Query All Records in the the Database
        query = text("SELECT * FROM Student_Data")
        student_df = pd.read_sql(query, conn)
        
    except:
        print("No data Available")
        
    return student_df

In [4]:
# Create a base class for declarating class definitions to produce Table objects
Base = declarative_base()

In [5]:
class Student(Base):
    __tablename__ = "Student_Data"
    
    Gender  = Column(String),
    Age = Column(String),
    Education_Level = Column(String),
    Institution_Type = Column(String),
    IT_Student = Column(String),
    Student_Location = Column(String),
    Load_Shedding = Column(String),
    Financial_Condition = Column(String),
    Internet_Type = Column(String),
    Network_Type = Column(String),
    Class_Duration = Column(String),
    Self_Lms = Column(String),
    Device = Column(String),
    Adaptivity_Level = Column(String),
    Student_ID = Column(Integer, primary_key = True)

/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Gender': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Age': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Education_Level': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Institution_Type': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'IT_Student': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Student_Location': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Load_Shedding': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Financial_Condition': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Internet_Type': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Network_Type': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Class_Duration': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Self_Lms': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Device': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):
/var/folders/tx/sr99h3gn7plb88mpxvnnnj3m0000gn/T/ipykernel_58271/3987325553.py:1: SAWarning: Ignoring declarative-like tuple value of attribute 'Adaptivity_Level': possibly a copy-and-paste error with a comma accidentally placed at the end of the line?
  class Student(Base):

In [13]:
# Load into dataframe
student_df = LoadData()
student_df

,student_id,gender,age,education_level,institution_type,it_student,student_location,load_shedding,financial_condition,internet_type,network_type,class_duration,self_lms,device,adaptivity_level
0,1,Boy,21-25,University,Non Government,No,Yes,Low,Mid,Wifi,4G,3-6,No,Tab,Moderate
1,2,Girl,21-25,University,Non Government,No,Yes,High,Mid,Mobile Data,4G,1-3,Yes,Mobile,Moderate
2,3,Girl,16-20,College,Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Moderate
3,4,Girl,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,4G,1-3,No,Mobile,Moderate
4,5,Girl,16-20,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,0,No,Mobile,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,1201,Girl,16-20,College,Non Government,No,Yes,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1201,1202,Girl,16-20,College,Non Government,No,No,High,Mid,Wifi,4G,3-6,No,Mobile,Moderate
1202,1203,Boy,11-15,School,Non Government,No,Yes,Low,Mid,Mobile Data,3G,1-3,No,Mobile,Moderate
1203,1204,Girl,16-20,College,Non Government,No,No,Low,Mid,Wifi,4G,1-3,No,Mobile,Low
1204,1205,Girl,11-15,School,Non Government,No,Yes,Low,Poor,Mobile Data,3G,1-3,No,Mobile,Moderate